mod.mc_dep_fabric=~26.1
deps.minecraft=26.1.2

deps.fabric_loader=2.5.85+0.19.3+26.1.2
deps.fabric_api=0.155.2+26.1.2+3.4.4
deps.neoforge=26.1.2.87

deps.surveyor=1.2.4-launchpad+26.1
deps.hoofprint=1.3.0-launchpad+26.1
deps.mcqoy=0.4.1+fabric-26.1
deps.yacl=3.9.6+26.1-neoforge
deps.modmenu=18.0.0-beta.1
deps.trinkets=4.0.0-beta.3+26.1
deps.immersive_overlays=1.7.0+26.1.2-neoforge

deps.launchpad=1.9.0+26.1.2

deps.fabric_base=2.0.3+b11575294c
deps.fabric_key_mapping=2.0.4+05fccb0f4c
deps.fabric_networking=6.3.1+2d8a89744c
deps.fabric_lifecycle_events=4.1.1+150d8dbd4c
deps.fabric_commands=3.0.5+29e133704c
deps.fabric_rendering=23.3.1+9e54f1904c
deps.fabric_events_interaction=5.2.2+7e69f0e84c