mod.mc_dep_fabric=~26.2
deps.minecraft=26.2

deps.fabric_loader=2.5.85+0.19.3+26.1.2
deps.fabric_api=0.161.0+26.2+4.0.0
deps.neoforge=26.2.0.88

deps.surveyor=1.2.4-launchpad+26.2
deps.hoofprint=1.3.0-launchpad+26.2
deps.mcqoy=0.4.1+fabric-26.1
deps.yacl=3.9.6+26.2-neoforge
deps.modmenu=20.0.3
deps.trinkets=4.1.0-beta.2+26.2
deps.immersive_overlays=1.8.5+26.2-neoforge

deps.launchpad=1.10.0+26.2

deps.fabric_base=2.0.4+d41ec0009e
deps.fabric_commands=3.1.0+0f1891179e
deps.fabric_events_interaction=5.2.8+df4186689e
deps.fabric_key_mapping=2.0.5+ce13d5789e
deps.fabric_networking=6.3.4+0c25d7489e
deps.fabric_lifecycle_events=4.1.4+d89c76349e
deps.fabric_rendering=25.3.3+d89c76349e
